name: Windows Release

on:
  push:
    branches:
      - 'master'
      - 'workflow-test'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'workflow-test'

defaults:
  run:
    shell: powershell

env:
  SOURCE_DIR: ${{ github.workspace }}
  QT_VERSION: '6.5.3'
  ARTIFACT: 'nahidanotes-build.zip'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: (1) Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: (2) Get all tags for correct version determination
        run: git fetch --all --tags -f

      - name: (3) Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: win64_msvc2019_64
          dir: ${{ runner.temp }}
          setup-python: false

      - name: (4) Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: (5) Build
        run: |
          cmake -B ${{ runner.temp }}/build -S ${{ env.SOURCE_DIR }}
          cmake --build ${{ runner.temp }}/build --config Release --target NahidaNotes

      - name: (6) Zip build
        run: Compress-Archive -Path ${{ runner.temp }}/build/NahidaNotes.exe -DestinationPath ${{ runner.temp }}/${{ env.ARTIFACT }}

      - name: (7) Save build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ runner.temp }}/${{ env.ARTIFACT }}
