name: Windows Release

on:
  push:
    branches:
      - 'master'
      - 'workflow-test'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'workflow-test'

defaults:
  run:
    shell: powershell

env:
  SOURCE_DIR: ${{ github.workspace }}
  QT_VERSION: '6.5.3'
  ARTIFACT: 'nahidanotes-build.zip'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: (1) Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: (2) Get all tags for correct version determination
        run: git fetch --all --tags -f

      - name: (3) Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: win64_msvc2019_64
          dir: ${{ runner.temp }}
          setup-python: false

      - name: (4) Download JOM
        run: |
          Invoke-WebRequest -Uri 'http://download.qt.io/official_releases/jom/jom.zip' -OutFile jom.zip

      - name: (5) Unzip JOM
        run: Expand-Archive -Path jom.zip -DestinationPath ${{ runner.temp }}/jom

      - name: (6) Create build directory
        run: New-Item -Path ${{ runner.temp }}/build -ItemType Directory

      - name: (7) Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: (8) Build
        run: |
          Write-Output "SOURCE_DIR: $env:SOURCE_DIR"
          Write-Output "RUNNER_TEMP: $env:RUNNER_TEMP"
          cmake -B ${{ runner.temp }}/build -S ${{ env.SOURCE_DIR }}
          ls ${{ runner.temp }}/build
          Get-Content ${{ runner.temp }}/build/CMakeFiles/CMakeError.log
          Get-Content ${{ runner.temp }}/build/CMakeFiles/CMakeOutput.log

      - name: (9) Zip build
        run: Compress-Archive -Path ${{ runner.temp }}/build/* -DestinationPath ${{ runner.temp }}/${{ env.ARTIFACT }}

      - name: (10) Save build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ runner.temp }}/${{ env.ARTIFACT }}
